# Change these first
owner: tiarebalbi
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: tiarebalbi.com
    url: https://tiarebalbi.com
  - name: Quaer
    url: https://quaer.cloud
  - name: Grupo Fortaleza
    url: https://grupofortalezaserv.com
  - name: Intranet
    url: https://intranet.grupofortalezaserv.com

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: uptime.tiarebalbi.com
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** monitor and status page, powered entirely by GitHub."
  introMessage: List of site monitored.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

assignees: # Users to assign downtime issues (optional)
  - tiarebalbi
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
